[workspace]
resolver = "2"
members = [
    "day01/puzzle1",
    "day01/puzzle2",
    "day02/puzzle1",
    "day02/puzzle2",
    "day03/puzzle1",
    "day03/puzzle2",
    "day04/puzzle1",
    "day04/puzzle2",
]